Seq-entry ::= seq {
  id {
    other {
      name "NZ_AKKP01000000",
      accession "NZ_AKKP00000000",
      version 1
    },
    general {
      db "NCBI_GENOMES",
      tag id 7828
    },
    gi 397738134
  },
  descr {
    title "Rhodococcus sp. JVH1",
    source {
      org {
        taxname "Rhodococcus sp. JVH1",
        db {
          {
            db "taxon",
            tag id 745408
          }
        },
        orgname {
          name binomial {
            genus "Rhodococcus",
            species "sp. JVH1"
          },
          mod {
            {
              subtype strain,
              subname "JVH1"
            }
          },
          lineage "Bacteria; Actinobacteria; Actinobacteridae;
 Actinomycetales; Corynebacterineae; Nocardiaceae; Rhodococcus",
          gcode 11,
          div "BCT"
        }
      },
      subtype {
        {
          subtype country,
          name "Canada"
        }
      }
    },
    molinfo {
      biomol genomic,
      tech wgs
    },
    pub {
      pub {
        sub {
          authors {
            names std {
              {
                name name {
                  last "Brooks",
                  first "Shannon",
                  initials "S.L."
                }
              },
              {
                name name {
                  last "Van Hamme",
                  first "Jonathan",
                  initials "J.D."
                }
              }
            },
            affil std {
              affil "Thompson Rivers University",
              div "Biological Sciences",
              city "Kamloops",
              sub "BC",
              country "Canada",
              street "Box 3010 900 McGill Road",
              postal-code "V2C 5N3"
            }
          },
          date std {
            year 2012,
            month 6,
            day 3
          }
        }
      }
    },
    pub {
      pub {
        article {
          title {
            name "Whole-genome shotgun sequence of Rhodococcus species strain
 JVH1."
          },
          authors {
            names std {
              {
                name name {
                  last "Brooks",
                  first "S",
                  initials "S.L."
                }
              },
              {
                name name {
                  last "Van Hamme",
                  first "J",
                  initials "J.D."
                }
              }
            },
            affil str "Department of Biological Sciences, Thompson Rivers
 University, Kamloops, British Columbia, Canada."
          },
          from journal {
            title {
              iso-jta "J. Bacteriol."
            },
            imp {
              date std {
                year 2012,
                month 10
              },
              volume "194",
              issue "19",
              pages "5492-5493",
              pubstatus ppublish
            }
          },
          ids {
            doi "10.1128/JB.01066-12",
            pubmed 22965106
          }
        },
        pmid 22965106
      }
    },
    comment "Contigs were aligned using Rhodococcus jostii RHA1 in
 NC_008268.1~Source bacteria can be obtained from Dr. Jonathan Van Hamme,
 Thompson Rivers University, Box 3010, 900 McGill Rd., Kamloops, BC, V2C 5N3
 Canada",
    user {
      type str "StructuredComment",
      data {
        {
          label str "StructuredCommentPrefix",
          data str "##Genome-Assembly-Data-START##"
        },
        {
          label str "Assembly Method",
          data str "GS De Novo Assembler v. 01/20/2010"
        },
        {
          label str "Genome Coverage",
          data str "30x"
        },
        {
          label str "Sequencing Technology",
          data str "454 GS FLX Titanium"
        },
        {
          label str "StructuredCommentSuffix",
          data str "##Genome-Assembly-Data-END##"
        }
      }
    },
    user {
      type str "WGSProjects",
      data {
        {
          label str "WGS_accession_first",
          data str "AKKP01000001"
        },
        {
          label str "WGS_accession_last",
          data str "AKKP01000173"
        }
      }
    },
    user {
      type str "WGS-Scaffold-List",
      data {
        {
          label str "Accession_first",
          data str "NZ_AKKP01000001"
        },
        {
          label str "Accession_last",
          data str "NZ_AKKP01000173"
        }
      }
    },
    user {
      type str "DBLink",
      data {
      }
    },
    user {
      type str "RefGeneTracking",
      data {
        {
          label str "Assembly",
          data fields {
            {
              label id 0,
              data fields {
                {
                  label str "accession",
                  data str "AKKP00000000"
                },
                {
                  label str "gi",
                  data int 396935310
                }
              }
            }
          }
        },
        {
          label str "Status",
          data str "WGS"
        }
      }
    },
    user {
      type str "GenomesInfo",
      data {
        {
          label str "Contigs",
          data int 173
        },
        {
          label str "Contributor",
          data str ""
        },
        {
          label str "URL",
          data str "-"
        },
        {
          label str "GenomeLink",
          data str ""
        },
        {
          label str "LocusTagLink",
          data str ""
        }
      }
    },
    user {
      class "Genome Size",
      type str "info",
      data {
        {
          label str "Size",
          data str "9.18"
        }
      }
    },
    user {
      type str "FeatureFetchPolicy",
      data {
        {
          label str "Policy",
          data str "OnlyNearFeatures"
        }
      }
    },
    user {
      type str "GenomeProjectsDB",
      data {
        {
          label str "ProjectID",
          data int 171304
        }
      }
    },
    create-date std {
      year 2012,
      month 7,
      day 25
    },
    update-date std {
      year 2013,
      month 3,
      day 15
    }
  },
  inst {
    repr virtual,
    mol dna,
    length 9181077,
    topology other
  }
}

