Seq-entry ::= seq {
  id {
    other {
      name "NZ_ABLL01000000",
      accession "NZ_ABLL00000000",
      version 1
    },
    general {
      db "NCBI_GENOMES",
      tag id 5972
    },
    gi 189215990
  },
  descr {
    title "Mycobacterium tuberculosis 94_M4241A",
    source {
      genome genomic,
      org {
        taxname "Mycobacterium tuberculosis 94_M4241A",
        db {
          {
            db "taxon",
            tag id 515615
          }
        },
        orgname {
          name binomial {
            genus "Mycobacterium",
            species "tuberculosis"
          },
          mod {
            {
              subtype strain,
              subname "94_M4241A"
            }
          },
          lineage "Bacteria; Actinobacteria; Actinobacteridae;
 Actinomycetales; Corynebacterineae; Mycobacteriaceae; Mycobacterium;
 Mycobacterium tuberculosis complex",
          gcode 11,
          div "BCT"
        }
      }
    },
    molinfo {
      biomol genomic,
      tech wgs
    },
    pub {
      pub {
        sub {
          authors {
            names std {
              {
                name name {
                  last "Small",
                  first "Peter",
                  initials "P."
                }
              },
              {
                name name {
                  last "Gagneux",
                  first "Sebastien",
                  initials "S."
                }
              },
              {
                name name {
                  last "Young",
                  first "Sarah",
                  initials "S."
                }
              },
              {
                name name {
                  last "Jaffe",
                  first "David",
                  initials "D."
                }
              },
              {
                name name {
                  last "Gnerre",
                  first "Sante",
                  initials "S."
                }
              },
              {
                name name {
                  last "Berlin",
                  first "Aaron",
                  initials "A."
                }
              },
              {
                name name {
                  last "Heiman",
                  first "David",
                  initials "D."
                }
              },
              {
                name name {
                  last "Hepburn",
                  first "Theresa",
                  initials "T."
                }
              },
              {
                name name {
                  last "Sykes",
                  first "Sean",
                  initials "S."
                }
              },
              {
                name name {
                  last "Alvarado",
                  first "Lucia",
                  initials "L."
                }
              },
              {
                name name {
                  last "Hopewell",
                  first "Philip",
                  initials "P."
                }
              },
              {
                name name {
                  last "Lander",
                  first "Eric",
                  initials "E."
                }
              },
              {
                name name {
                  last "Galagan",
                  first "James",
                  initials "J."
                }
              },
              {
                name name {
                  last "Nusbaum",
                  first "Chad",
                  initials "C."
                }
              },
              {
                name name {
                  last "Birren",
                  first "Bruce",
                  initials "B."
                }
              },
              {
                name consortium "The Broad Institute Genome Sequencing Platform"
              }
            },
            affil std {
              affil "Broad Institute of MIT and Harvard",
              city "Cambridge",
              sub "MA",
              country "USA",
              street "320 Charles Street",
              email "sequence_submissions@broad.mit.edu",
              postal-code "02141"
            }
          },
          date std {
            year 2008,
            month 5,
            day 13
          }
        }
      }
    },
    pub {
      pub {
        gen {
          cit "Unpublished",
          authors {
            names std {
              {
                name name {
                  last "Small",
                  first "Peter",
                  initials "P."
                }
              },
              {
                name name {
                  last "Gagneaux",
                  first "Sebastien",
                  initials "S."
                }
              },
              {
                name name {
                  last "Hopewell",
                  first "P",
                  initials "P."
                }
              },
              {
                name name {
                  last "Young",
                  first "Sarah",
                  initials "S.K."
                }
              },
              {
                name name {
                  last "Kodira",
                  first "Chinnappa",
                  initials "C.D."
                }
              },
              {
                name name {
                  last "Zeng",
                  first "Qiandong",
                  initials "Q."
                }
              },
              {
                name name {
                  last "Koehrsen",
                  first "Michael",
                  initials "M."
                }
              },
              {
                name name {
                  last "Alvarado",
                  first "Lucia",
                  initials "L."
                }
              },
              {
                name name {
                  last "Berlin",
                  first "Aaron",
                  initials "A."
                }
              },
              {
                name name {
                  last "Borenstein",
                  first "David",
                  initials "D."
                }
              },
              {
                name name {
                  last "Chen",
                  first "Zehua",
                  initials "Z."
                }
              },
              {
                name name {
                  last "Engels",
                  first "Reinhard",
                  initials "R."
                }
              },
              {
                name name {
                  last "Freedman",
                  first "Edward",
                  initials "E."
                }
              },
              {
                name name {
                  last "Gellesch",
                  first "Marcel",
                  initials "M."
                }
              },
              {
                name name {
                  last "Goldberg",
                  first "Jonathan",
                  initials "J."
                }
              },
              {
                name name {
                  last "Griggs",
                  first "Allison",
                  initials "A."
                }
              },
              {
                name name {
                  last "Gujja",
                  first "Sharvari",
                  initials "S."
                }
              },
              {
                name name {
                  last "Heiman",
                  first "David",
                  initials "D."
                }
              },
              {
                name name {
                  last "Hepburn",
                  first "Theresa",
                  initials "T."
                }
              },
              {
                name name {
                  last "Howarth",
                  first "Clint",
                  initials "C."
                }
              },
              {
                name name {
                  last "Jen",
                  first "Dennis",
                  initials "D."
                }
              },
              {
                name name {
                  last "Larson",
                  first "Lisa",
                  initials "L."
                }
              },
              {
                name name {
                  last "Lewis",
                  first "Bil",
                  initials "B."
                }
              },
              {
                name name {
                  last "Mehta",
                  first "Teena",
                  initials "T."
                }
              },
              {
                name name {
                  last "Park",
                  first "Danny",
                  initials "D."
                }
              },
              {
                name name {
                  last "Pearson",
                  first "Matt",
                  initials "M."
                }
              },
              {
                name name {
                  last "Roberts",
                  first "Andrew",
                  initials "A."
                }
              },
              {
                name name {
                  last "Saif",
                  first "Sakina",
                  initials "S."
                }
              },
              {
                name name {
                  last "Shea",
                  first "Terrance",
                  initials "T."
                }
              },
              {
                name name {
                  last "Shenoy",
                  first "Narmada",
                  initials "N."
                }
              },
              {
                name name {
                  last "Sisk",
                  first "Peter",
                  initials "P."
                }
              },
              {
                name name {
                  last "Stolte",
                  first "Christian",
                  initials "C."
                }
              },
              {
                name name {
                  last "Sykes",
                  first "Sean",
                  initials "S."
                }
              },
              {
                name name {
                  last "Walk",
                  first "Thomas",
                  initials "T."
                }
              },
              {
                name name {
                  last "White",
                  first "Jared",
                  initials "J."
                }
              },
              {
                name name {
                  last "Yandava",
                  first "Chandri",
                  initials "C."
                }
              },
              {
                name name {
                  last "Nusbaum",
                  first "Chad",
                  initials "C."
                }
              },
              {
                name name {
                  last "Galagan",
                  first "James",
                  initials "J."
                }
              },
              {
                name name {
                  last "Birren",
                  first "Bruce",
                  initials "B."
                }
              },
              {
                name consortium "The Broad Institute Genome Sequencing Platform"
              }
            },
            affil std {
              affil "Broad Institute of MIT and Harvard",
              city "Cambridge",
              sub "MA",
              country "USA",
              street "7 Cambridge Center",
              email "sequence_submissions@broad.mit.edu",
              postal-code "02142"
            }
          },
          title "Annotation of Mycobacterium tuberculosis strain 94_M4241A"
        }
      }
    },
    comment "Genome Coverage: 9x (7.7x Q>20)~Sequencing Technology:
 ABI~Annotation was added to the scaffolds in June 2010.",
    user {
      type str "WGSProjects",
      data {
        {
          label str "WGS_accession_first",
          data str "ABLL01000001"
        },
        {
          label str "WGS_accession_last",
          data str "ABLL01000192"
        }
      }
    },
    user {
      type str "WGS-Scaffold-List",
      data {
        {
          label str "Accession_first",
          data str "NZ_DS985170"
        },
        {
          label str "Accession_last",
          data str "NZ_DS985179"
        }
      }
    },
    user {
      type str "RefGeneTracking",
      data {
        {
          label str "Assembly",
          data fields {
            {
              label id 0,
              data fields {
                {
                  label str "accession",
                  data str "ABLL00000000"
                },
                {
                  label str "gi",
                  data int 189212844
                }
              }
            }
          }
        },
        {
          label str "Status",
          data str "WGS"
        }
      }
    },
    user {
      type str "GenomesInfo",
      data {
        {
          label str "Contigs",
          data int 192
        },
        {
          label str "Contributor",
          data str "Broad Institute"
        },
        {
          label str "URL",
          data str "http://www.broad.mit.edu/"
        },
        {
          label str "GenomeLink",
          data str "http://www.broadinstitute.org"
        },
        {
          label str "LocusTagLink",
          data str ""
        }
      }
    },
    user {
      class "Genome Size",
      type str "info",
      data {
        {
          label str "Size",
          data str "4.41"
        }
      }
    },
    user {
      type str "DBLink",
      data {
        {
          label str "BioProject",
          num 1,
          data strs {
            "PRJNA55095"
          }
        }
      }
    },
    user {
      type str "GenomeProjectsDB",
      data {
        {
          label str "ProjectID",
          data int 55095
        },
        {
          label str "ParentID",
          data int 0
        }
      }
    },
    create-date std {
      year 2008,
      month 5,
      day 30
    },
    update-date std {
      year 2010,
      month 6,
      day 17
    }
  },
  inst {
    repr virtual,
    mol dna,
    length 4410654,
    topology other
  }
}

